spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        ## system-server 服务
        - id: system-admin-api # 路由的编号
          uri: lb://system-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/system/**
          filters:
              - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: system-pub-api # 路由的编号
          uri: lb://system-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/pub-api/system/**
          filters:
              - RewritePath=/pub-api/system/v3/api-docs, /v3/api-docs
        ## product-server 服务
        - id: product-admin-api # 路由的编号
          uri: lb://product-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/product/**
          filters:
            - RewritePath=/admin-api/product/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
#            - name: RateLimiterFactory
#              args:
#                url: /admin-api/product/sku/query
        - id: product-pub-api # 路由的编号
          uri: lb://product-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/pub-api/product/**
          filters:
            - RewritePath=/pub-api/product/v3/api-docs, /v3/api-docs
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/system 前缀
knife4j:
  swagger2:
    enable-parameter-scanner: true
    config:
      headers:
        - name: Authorization
          description: 认证 token
          in: header
          type: string
          default: Bearer test1
  gateway:
    enabled: true
    routes:
      - name: system-server
        service-name: system-server
        url: /admin-api/system/v3/api-docs
      - name: product-server
        service-name: product-server
        url: /admin-api/product/v3/api-docs

--- #################### 项目相关配置 ####################

newaim:
  daily-limit: 100
  info:
    version: 1.0.0
